### PR TITLE
Support for Class#cast(Object) and Class#isInstance(Object)

### PR DESCRIPTION
**Pull request by mfilser**
Hello @maximeAudrain,
here is a new Option for your Jenerate Plugin to use the Method Class#cast(Object) and Class#isInstance(Object).
I am not familiar with the Eclipse Development, but it works as expected. The only Option what is missing is to disable and uncheck the box "Use class comparison instead of instanceOf.

Let me know what you think about the new feature.

Best regards
Martin

### CODE REVIEW

**Comment by maximeAudrain** [comment]
Hi Martin,

I will take a look at your pull request this week in order to integrate it ASAP. At the same time, I'll check the option you describe to switch between features. I'll let you know how it goes :)

Cheers,

Maxime

**Comment by maximeAudrain** [comment]
Hi Martin,

I just merged your pull request : works like a charm! Thanks! :)
Concerning the uncheck and disabling of the "Use class comparison instead of instanceOf.", I think people could use both your option and this one : the result would be that the equals implementation would use class comparison but the afterward cast would use the Class.cast(Object) that you implemented. And with the checkboxes values being cached even when the dialog is closed, it allows people to keep their preferred settings at all time. So IMO I think it is good enough with the current implementation :) !

Please, if you have other questions or pull requests, I would be happy to answer!

I will deploy a new release pretty soon so anyone can use it!

Cheers,

Maxime

**Comment by mfilser** [comment]
Hello maximeAudrain,
ok, i think that's ok with the checkbox.
Thanks for your merge ;)

Regards,
Martin

**Comment by maximeAudrain** [comment]
Dear Martin,

Sorry for the long delay, I just deployed the plugin under version 1.0.2 with the changes you made from this pull request.

Please have a look and tell me if it is OK?

Cheers,

Maxime

**Comment by mfilser** [comment]
Hello Maxime,
no Problem, i used the git version all the time.
I just installed version 1.0.2 and everything works fine, thanks ;)

Cheers,
Martin

**Pull request merged**
