### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by mwensveen-nl**
Added two small features:

Add tooltip on the toString dialog that shows how the output of the
toString() would look like (based on the javadoc)

Add the option to use getClass instead of instanceof in the equals
method

### CODE REVIEW

**Comment by mwensveen-nl** [comment]
Processed the comments and merged with upstream commits

**Comment by maximeAudrain** [comment]
Ok, that looks perfect!! I'll do the merge probably ASAP :)

**Comment by maximeAudrain** [comment]
Hi mwensveen-nl

The plugin is ready to be used! Your pull request is integrated in the release!

Please have a look here for information on the plugin and how to install it : http://maximeaudrain.github.io/

If you have any feedbacks, issues, etc... feel free to post them on https://github.com/maximeAudrain/jenerate

Cheers,

Maxime

**Comment by melloware** [comment]
Maxime,

I just downloaded from Marketplace and it works great!  I just notified all my friends about your plugin.

Mello

**Comment by mwensveen-nl** [comment]
Maxime,

Installed the plugin using the updatesite. Works great.
Thanks for reviving the dead commens4e plugin.

Micha

**Pull request merged**
